name: CI/CD API Star Wars

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Clona o repositório
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Configura Docker Buildx (para build eficiente)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 3. Login no Docker Hub (opcional, se for publicar a imagem)
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 4. Build da imagem com Docker Compose
      - name: Build Docker image
        run: docker-compose build

      # 5. Testa se containers sobem corretamente
      - name: Run containers
        run: docker-compose up -d

      # 6. Testa se Apache está rodando
      - name: Test HTTP Response
        run: |
          sleep 10
          curl -I http://localhost:8080 || exit 1

      # 7. (Opcional) Publica a imagem no Docker Hub
      - name: Push Docker image
        if: github.ref == 'refs/heads/main'
        run: docker-compose push
