name: CI/CD API Star Wars

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: api
          MYSQL_USER: admin
          MYSQL_PASSWORD: 123
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: docker-compose build

      - name: Run containers
        run: docker-compose up -d

      - name: Wait for Apache
        run: |
          echo "Esperando o container subir..."
          sleep 15

      - name: Test HTTP response inside container
        run: |
          docker exec apache_php curl -I http://localhost || exit 1

      - name: Shut down containers
        run: docker-compose down
